### ISSUE TITLE
仓库名拼写错误

### ISSUE THREAD

**Issue by ice1000** [Glavo/JavaUtilities#1]
Utilities
:joy:interesting

**Comment by TooYoungTooSimp** [comment]
+1

**Comment by Glavo** [comment]
尴尬

![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f602.png)已修改

**Comment by ice1000** [comment]
这是坠吼的。另外楼上那个垃圾桶头像的是个大佬。
